### ISSUE TITLE
Reconsider the contact form in footer section

### ISSUE THREAD

**Issue by DennisAlund** [kumpul/kumpul-website-jekyll#4]
The contact form in the footer should preferably be moved to a separate contact page, and only exist there. E.g. `https://www.kumpul.co/contact/`

[Formspree](https://formspree.io/) that we're using to manage the contact form requests is counting each originating URL as a unique issuer that needs to be validated. Which means that every single page on our website needs to be validated.

What we need to figure out is: what to we present in the footer if we're taking away the contact form?

**Comment by ArjenK96** [comment]
Still need to validate domain.com/contact/ when it is pushed to master branch. /contact/index or /contact/index.html are also valid URL's for the page, but I doubt anyone will get on these links.

**Comment by DennisAlund** [comment]
Thanks @ArjenK96 I've validated the originating paths as mentioned
