### ISSUE TITLE
Make header/splash image anchor to the center

### ISSUE THREAD

**Issue by DennisAlund** [kumpul/kumpul-website-jekyll#7]
It seems to be anchored to the left. When the window is minimized to mobile size, it crops out the right part of the group.

![image](https://cloud.githubusercontent.com/assets/2051607/22862261/70812774-f166-11e6-93b3-ea4f57ace31e.png)

![image](https://cloud.githubusercontent.com/assets/2051607/22862282/b870578a-f166-11e6-8ef3-e8c84ec824df.png)

**Comment by Erwinkok** [comment]
closed #7
