### ISSUE TITLE
Change color scheme according to branding

### ISSUE THREAD

**Issue by DennisAlund** [kumpul/kumpul-website-jekyll#8]

**Comment by ArjenK96** [comment]
Other colours do not really look good

**Comment by DennisAlund** [comment]
@Arjenk96 can you please add a couple of screenshots to convince @afterarainyday ;-)

**Comment by Erwinkok** [comment]
What do you thing of the current color? It is the same color as where the blue and the green/yellowish comes together. I thing this look great and is still according to the branding color schema!? @DennisAlund @ArjenK96 @afterainyday @slahibu

**Comment by DennisAlund** [comment]
For me, I don't have any issues with the current color. I agree that it's not our branding color, but then again, I am practically color blind when it comes to what looks right or wrong.

**Comment by DennisAlund** [comment]
@ArjenK96 but perhaps @afterainyday can see the options before knowing what he's saying yes or no to :-) Please add screenshots of what you showed me before so that we can see the intensity of using the colors from our logo.

**Comment by Erwinkok** [comment]
This was the color before
![Uploading Schermafbeelding 2017-02-17 om 10.13.32.PNG…]()

**Comment by Erwinkok** [comment]
This is where I changed it to
![Uploading Schermafbeelding 2017-02-17 om 10.13.54.PNG…]()

**Comment by afterainyday** [comment]
I have trouble opening the screenshot, it's leading me to the top of the issue topic every time I click it.

**Comment by Erwinkok** [comment]
Yes, happens to me too. It says it is still uploading and it has been for the last hour or so.. I don't know whats wrong, but I send you the screenshots in the slack/website thread as well
