### ISSUE TITLE
Improve CTAs

### ISSUE THREAD

**Issue by DennisAlund** [kumpul/kumpul-website-jekyll#9]
- [x] Make buttons in sidebar fill the whole box width with class attribute `fit`
- [x] Be more explicit in with texts like _"Check our pricing"_ or something

**Comment by Erwinkok** [comment]
Made the buttons in the sidebar fill the whole box width

**Comment by DennisAlund** [comment]
Added a more explicit button for "membership options" on the splash image on landing page in commit 3024c6870952c7e10b6a7e82e6015aab47edd863

**Comment by DennisAlund** [comment]
> Made the buttons in the sidebar fill the whole box width

@Erwinkok insert reference to the commit pls
